- name: create AWS resources
  hosts: localhost
  connection: local
  gather_facts: false
  tasks:
  - name: create an EC2 instance
    local_action:
      module: ec2
      region: us-west-1
      key_name: AWS_EC2_VAGRANT
      instance_type: t2.micro
      image: ami-11780271
      wait: yes
      count: 1
      vpc_subnet_id: subnet-b0f2a1f6
      group: RDB
      assign_public_ip: yes
    register: basic_ec2

  - name: install 10Gen repo
    copy: src=10gen.repo.j2 dest=/etc/yum.repos.d/10gen.repo

  - name: Create the mongod user
    user: name=mongod comment="MongoD"
