- hosts: all
  gather_facts: yes
  remote_user: root
  become: true
  vars:
    java8_download_url: http://download.oracle.com/otn-pub/java/jdk/8u91-b14/jdk-8u91-linux-x64.tar.gz
    java8_download_folder: /opt
    java_name: "{{download_folder}}/jdk1.8.0_91"
    java_archive: "{{download_folder}}/jdk-8u91-linux-x64.tar.gz"
  tasks:

    - name: update hosts file
      lineinfile:
        dest=/etc/hosts
        regexp='{{ item }}.*$'
        line="{{ item }} {{ hostvars[item].host_alias }}"
        state=present
      with_items: groups['all']

    - name: install elasticsearch repository GPG key


    - name: install elasticsearch repo
      rpm_key: 
        state=present 
        key=https://packages.elastic.co/GPG-KEY-elasticsearch
      copy: src=templates/elasticsearch.repo dest=/etc/yum.repos.d/ owner=root group=root mode=0644

    - name: install epel-release
      yum: name=epel-release state=latest

    - name: install oracle java8
      get_url: 
        url={{java_download_url}}
        headers="Cookie: gpw_e24=http%3A%2F%2Fwww.oracle.com%2F; oraclelicense=accept-securebackup-cookie"
        validate_certs=no
        dest={{java_archive}}
      unarchive:
        src={{java_archive}}
        dest={{download_folder}}
        copy=no
      file: 
        state=directory 
        path={{java_name}}
        owner=root 
        group=root 
        recurse=yes
      command: 'alternatives --install "/usr/bin/java" "java" "{{java_name}}/bin/java" 2000'
      file:
        state=absent
        path={{java_archive}}

    - name: install packages
      yum: pkg={{item}} state=latest
      with_items:
        - net-tools
        - jq
        - python-pip
        - git

    - name: install elasticsearch
      yum: name=elasticsearch state=latest

    - name: add elasticsearch service to chkconfig
      shell: chkconfig --add elasticsearch

    - name: set cluster name
      lineinfile: 'dest=/etc/elasticsearch/elasticsearch.yml
        state=present 
        insertafter="^# cluster.name" 
        line="cluster.name: w210"'

    - name: set cluster node name
      lineinfile: 'dest=/etc/elasticsearch/elasticsearch.yml
        state=present 
        insertafter="^# node.name" 
        line="node.name: {{ hostvars[inventory_hostname].host_alias }}"'

    - name: set node as data node
      lineinfile: 'dest=/etc/elasticsearch/elasticsearch.yml
        state=present 
        insertafter="^node.name" 
        line="node.data: true"'

    - name: set network.host
      lineinfile: 'dest=/etc/elasticsearch/elasticsearch.yml
        state=present 
        insertafter="^# network.host" 
        line="network.host: {{ inventory_hostname }}"'

    - name: set network.bind
      lineinfile: 'dest=/etc/elasticsearch/elasticsearch.yml
        state=present 
        insertafter="^network.host" 
        line="network.bind_host: {{ inventory_hostname }}"'

    - name: disable multicast discovery
      lineinfile: 'dest=/etc/elasticsearch/elasticsearch.yml
        state=present 
        insertafter="^# discovery.zen.ping.unicast.hosts" 
        line="discovery.zen.ping.multicast.enable: false"'

    - name: set discovery node list
      lineinfile: 'dest=/etc/elasticsearch/elasticsearch.yml
        state=present 
        insertafter="^discovery.zen.ping.multicast.enable" 
        line="discovery.zen.ping.unicast.hosts: [\"{% for host in groups["all"] %}{{ hostvars[host].host_alias }}\"{%if not loop.last %},\"{% endif %}{% endfor %}]"'

    - name: install jettro plugin
      command: /usr/share/elasticsearch/bin/plugin install royrusso/elasticsearch-HQ
        creates=/usr/share/elasticsearch/plugins/gui/package.json

    - name: enable cors
      lineinfile: 'dest=/etc/elasticsearch/elasticsearch.yml
        state=present 
        insertafter=EOF
        line="http.cors.enabled: true"'
    - name: enable cors origin
      lineinfile: 'dest=/etc/elasticsearch/elasticsearch.yml
        state=present 
        insertafter=EOF
        line="http.cors.allow-origin: \"http://www.gridshore.nl\""' 

    - name: install python modules
      sudo: true
      pip: name={{item}}
      with_items:
        - elasticsearch
        - softlayer-object-storage    

- hosts: master
  remote_user: root
  tasks:

    - name: set node as master node
      lineinfile: 'dest=/etc/elasticsearch/elasticsearch.yml
        state=present 
        insertafter="^node.data" 
        line="node.master: true"'

    - name: start master node elasticsearch service
      shell: service elasticsearch start

- hosts: datanodes
  remote_user: root
  tasks:

    - name: start data node elasticsearch service
      shell: service elasticsearch start     
